GET http://localhost:3001/api/blogs

### Create New Blog after login
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2NDg4YTM4M2YxMDk4Y2FhMWQ0MjJkM2UiLCJpYXQiOjE2ODY2NzYzOTMsImV4cCI6MTY4NjY3OTk5M30.XjHKAgj936dc3LV5OUc0y4A8Q4CW34pQLGp52Gq_exs

{
    "title": "United",
    "author": "Nations",
    "url": "132321323123",
    "likes": 22
}

### Edit Recipe
PUT http://localhost:3001/api/blogs/6488a3d1f1098caa1d422d49
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2NDg4YTM4M2YxMDk4Y2FhMWQ0MjJkM2UiLCJpYXQiOjE2ODY2NzYzOTMsImV4cCI6MTY4NjY3OTk5M30.XjHKAgj936dc3LV5OUc0y4A8Q4CW34pQLGp52Gq_exs

{
    "title": "Bougie",
    "author": "The Master",
    "url": "BougieOugie",
    "likes": 68
}

### Delete
DELETE http://localhost:3001/api/blogs/6488a3d1f1098caa1d422d49
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2NDg4YTM4M2YxMDk4Y2FhMWQ0MjJkM2UiLCJpYXQiOjE2ODY2NzYzOTMsImV4cCI6MTY4NjY3OTk5M30.XjHKAgj936dc3LV5OUc0y4A8Q4CW34pQLGp52Gq_exs

### Get individual Recipe
GET http://localhost:3001/api/blogs/6488a3d1f1098caa1d422d49


